name: Publish GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Convert Markdown into HTML and PDF
        uses: KoharaKazuya/marp-cli-action@v4

      - name: Uploade artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  pdf-push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    steps:
      - name: safe dirctory
        run: git config --global --add safe.directory $(pwd)
      - name: ls
        run: ls -l
      - name: Commit changes
        if: success()
        run: |
          git add ./*.pdf
          git status
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update pdf" && git push)
